In [1]:
import pandas as pd
import numpy as np

In [31]:
wines = pd.DataFrame(data={'Şarap': ['Pellehaut Kırmızı Şarap', 'Finca Las Zarras Kırmızı Şarap', 
                                     'Ed Knows Cabernet Sauvignon Kırmızı Sek Şarap', 
                                     'El Paso Kırmızı Şarap', 'Tersus Cabernet Sauvignon Kırmızı Şarap', 
                                     'Chateau Argadens Kırmızı Şarap', 
                                     'Piccini Pinocchio Kırmızı Yarı Tatlı Şarap', 
                                     'Sevilen İsabey Cabernet Sauvignon Merlot', 
                                     'Doluca Sarafin Fume Blanc', 
                                     'Piccini Prosecco Doğal Köpüren Beyaz Şarap'],
                           
                           'Ülke': ['Fransa', 'İspanya', 'Moldova', 'İspanya', 'Moldova', 'Fransa', 
                                    'İtalya', 'Türkiye', 'Türkiye', 'İtalya'], 
                           
                           'Fiyat': [1193.33, 646.67, 613.2, 700, 686.67, 1399.87, 1366.67, 
                                     1006.67, 2753.33, 2653.33],
                           
                           'AlkolOran': [11.5, 11, 13, 13.5, 12.5, 14, 13, 13.5, 13, 11]})

wines

                                           Şarap     Ülke    Fiyat  AlkolOran
0                        Pellehaut Kırmızı Şarap   Fransa  1193.33       11.5
1                 Finca Las Zarras Kırmızı Şarap  İspanya   646.67       11.0
2  Ed Knows Cabernet Sauvignon Kırmızı Sek Şarap  Moldova   613.20       13.0
3                          El Paso Kırmızı Şarap  İspanya   700.00       13.5
4        Tersus Cabernet Sauvignon Kırmızı Şarap  Moldova   686.67       12.5
5                 Chateau Argadens Kırmızı Şarap   Fransa  1399.87       14.0
6     Piccini Pinocchio Kırmızı Yarı Tatlı Şarap   İtalya  1366.67       13.0
7       Sevilen İsabey Cabernet Sauvignon Merlot  Türkiye  1006.67       13.5
8                      Doluca Sarafin Fume Blanc  Türkiye  2753.33       13.0
9     Piccini Prosecco Doğal Köpüren Beyaz Şarap   İtalya  2653.33       11.0

In [32]:
wines[['Fiyat', 'AlkolOran']].corr()

              Fiyat  AlkolOran
Fiyat      1.000000  -0.165381
AlkolOran -0.165381   1.000000